#defining services we want to run in our container

version: "3.4"

services:
  app:
    build: .
    container_name: academy_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./django_academy/envs/.env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: academy_db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=01.django_academy
      - PGDATA= /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data










