#defining services we want to run in our container

version: "3.4"

services:
  app:
    build: ./django_academy
    container_name: academy_app
    command: gunicorn django_academy.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/tmp/django_academy/staticfiles/
    ports:
      - 8000:8000
    env_file:
      - ./django_academy/envs/.env.prod
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: academy_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=01.django_academy
      - PGDATA= /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: academy_server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - app













